### ISSUE TITLE
Is it possible to have it with Bower ? 

### ISSUE THREAD

**Issue by thierryskoda** [indrimuska/angular-counter#2]
It would be so appreciated ! :) 

Thank you very much !

**Comment by indrimuska** [comment]
Hi @thierryskoda,
Angular Counter is already available with bower under the name [**angular-counter-animation**](http://bower.io/search/?q=angular-counter-animation).
That's because angular-counter was already taken! :smile: 

I know that I got to update the readme file to show that, because it's not so easy to find.
I will do it as soon as possible.

**Comment by thierryskoda** [comment]
Ok good thank you very much!
